development:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV["DATABASE_POOL"] || 25 %>
  url: "postgres://postgres@postgres:5432/berlin_development"

test:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV["DATABASE_POOL"] || 25 %>
  url: "postgres://postgres@postgres:5432/berlin_test"

production:
  adapter: mysql2
  database: berlin
  username: berlin
  password: Ohth8omah6aish4kei6oaPhaip9ahb3A
  pool: 5

