test:
  adapter: mysql2
  database: berlin_test
  username: root
  password: 
  pool: 5
  timeout: 5000

development:
  adapter: mysql2
  database: berlin_development
  host: localhost
  username: root
  password: 
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: berlin
  username: berlin
  password: Ohth8omah6aish4kei6oaPhaip9ahb3A
  pool: 5

