development:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV["DATABASE_POOL"] || 25 %>
  url: "postgres://postgres@postgres:5432/berlin_development"

test:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV["DATABASE_POOL"] || 25 %>
  url: "postgres://postgres@postgres:5432/berlin_test"

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV["DATABASE_POOL"] || 25 %>
  url: <%= ENV["DATABASE_URL"] %>

