test:
  adapter: mysql2
  database: berlin_test
  username: root
  password: password
  pool: 5
  timeout: 5000

development:
  adapter: mysql2
  database: berlin_development
  username: root
  password: password
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: berlin
  username: berlin
  password: uc6AhJienor9Ta8zai
  pool: 5

