test:
  adapter: mysql
  database: berlin_test
  username: root
  password: password
  pool: 5
  timeout: 5000

development:
  adapter: sqlite3
  database: db/berlin_development.sqlite3
  pool: 5
  timeout: 5000
